#version 460

layout(set = 0, binding = 0) buffer readonly restrict in_a { float a[]; };
layout(set = 0, binding = 1) buffer readonly restrict in_b { float b[]; };
layout(set = 0, binding = 2) buffer writeonly restrict out_c { float c[]; };

layout (local_size_x = 64) in;

layout(push_constant) uniform PushConstants {
    uint size;
};

void main()
{
    uint index = gl_GlobalInvocationID.x;

    if( index < size )
        c[index] = a[index] - b[index];
}